version: '2'

services:
    app:
        build: docker/app
        volumes:
            - ./:/var/www/html
        ports:
            - 80:80
        depends_on:
            - db
        environment:
            APP_APACHE_ROOT_DIR: /var/www/html

    db:
        image: mysql:5.6
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ukulele_dev
            MYSQL_USER: dev
            MYSQL_PASSWORD: dev
        volumes:
            - db:/var/lib/mysql

volumes:
    db: {}
